FROM registry.fedoraproject.org/fedora:31
LABEL maintainer="Randy Barlow <bowlofeggs@fedoraproject.org>"

RUN dnf install -y cargo
RUN cargo install cargo-license
RUN cd /rpick && cargo build

CMD ["bash"]
